// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Function$Rationale = require("rationale/src/Function.js");

function condLog(shouldLog, message) {
  if (shouldLog) {
    console.log(message);
    return /* () */0;
  } else {
    return 0;
  }
}

var greeting = "foo";

console.log("\n\n\n\n\n--------------------------------------------------------------------");

"Hello " + (String(greeting) + " from `console.log` using string templates");

var blockExpression = "" + (String("a") + (" and " + (String("b") + "")));

var switchExpressionParam = "marco";

var switchExpression = switchExpressionParam === "marco" ? "polo" : "Unnecessary catch all handler";

function doubleInt(x) {
  return (x << 1);
}

function doubleFloat(x) {
  return x * 2;
}

function log(param) {
  return 0;
}

function doubleString(param) {
  return Function$Rationale.$less$pipe$pipe((function (param) {
                return Function$Rationale.$less$pipe$pipe((function (prim) {
                              return String(prim);
                            }), doubleInt, param);
              }), Caml_format.caml_int_of_string, param);
}

Function$Rationale.$less$pipe$pipe(log, doubleString, "5");

function coinToString(x) {
  switch (x) {
    case 0 : 
        return "`x` was BTC";
    case 1 : 
        return "`x` was ETH";
    case 2 : 
        return "`x` was LTC";
    
  }
}

coinToString(/* BTC */0);

coinToString(/* ETH */1);

function log$1(param) {
  return 0;
}

function eitherToString(data) {
  if (data.tag) {
    var x = data[0];
    if (x !== 0) {
      return "Right(" + (String(x) + (", " + (String(data[1]) + ")")));
    } else {
      return "Right where the first was 0";
    }
  } else {
    return "Left(" + (String(data[0]) + ")");
  }
}

function eitherToStringLog(param) {
  return Function$Rationale.$less$pipe$pipe(log$1, eitherToString, param);
}

eitherToStringLog(/* Left */Block.__(0, ["Danger Will Robinson"]));

eitherToStringLog(/* Right */Block.__(1, [
        0,
        7
      ]));

eitherToStringLog(/* Right */Block.__(1, [
        52,
        104
      ]));

var rob = /* record */[
  /* name */"Rob",
  /* age */31
];

var ally = /* record */[
  /* name */"Ally",
  /* age */30
];

function getPersonInfo(data) {
  var exit = 0;
  switch (data[/* name */0]) {
    case "Ally" : 
    case "Rob" : 
        exit = 1;
        break;
    default:
      return "Some other person with the name: \"" + (data[/* name */0] + ("\" is " + (String(data[/* age */1]) + " years old.")));
  }
  if (exit === 1) {
    return "\"" + (String(data[/* name */0]) + ("\" is " + (String(data[/* age */1]) + " years old")));
  }
  
}

getPersonInfo(rob);

getPersonInfo(ally);

getPersonInfo(/* record */[
      /* name */"Jerry",
      /* age */82
    ]);

function getNameVerbose(data) {
  if (data[/* name */0] === "Rob") {
    return "What's up Rob";
  } else {
    return "I don\'t know you " + (String(data) + ".name");
  }
}

function getNameShort(x) {
  if (x[/* name */0] === "Rob") {
    return "What's up Rob";
  } else {
    return "I don\'t know you " + (String(x) + ".name");
  }
}

getNameVerbose(rob);

getNameShort(ally);

function findIndexValue(needle, haystack) {
  if (haystack.length !== 0) {
    return haystack.findIndex((function (x) {
                  return Caml_obj.caml_equal(x, needle);
                }));
  }
  
}

var someArray = /* array */[
  "foo",
  "bar",
  "baz"
];

findIndexValue("foo", someArray);

findIndexValue("baz", someArray);

findIndexValue("baz", someArray);

findIndexValue("bar", someArray);

findIndexValue("bar", someArray);

findIndexValue("bar", someArray);

function log$2(param) {
  return 0;
}

function speak(animal, extra) {
  log$2(animal[/* kind */0] ? "I\'m a smelly dog, I go by " + (String(animal) + (".name. Here\'s a thought about " + (String(extra) + "."))) : "Hi, I\'m a Cat by the name of " + (String(animal) + (".name and I want to tell you about " + (String(extra) + "!!"))));
  return animal;
}

var someCat = /* record */[
  /* kind : Cat */0,
  /* name */"pet1"
];

var someDog = /* record */[
  /* kind : Dog */1,
  /* name */"pet2"
];

speak(speak(someCat, "my paws"), "my tail");

speak(someDog, "poop");

var ifElseLet = "value is true";

var a = "file scope 'a'";

var btc = /* BTC */0;

var eth = /* ETH */1;

var ltc = /* LTC */2;

exports.condLog = condLog;
exports.greeting = greeting;
exports.ifElseLet = ifElseLet;
exports.a = a;
exports.blockExpression = blockExpression;
exports.switchExpressionParam = switchExpressionParam;
exports.switchExpression = switchExpression;
exports.doubleInt = doubleInt;
exports.doubleFloat = doubleFloat;
exports.doubleString = doubleString;
exports.btc = btc;
exports.eth = eth;
exports.ltc = ltc;
exports.coinToString = coinToString;
exports.eitherToString = eitherToString;
exports.eitherToStringLog = eitherToStringLog;
exports.rob = rob;
exports.ally = ally;
exports.getPersonInfo = getPersonInfo;
exports.getNameVerbose = getNameVerbose;
exports.getNameShort = getNameShort;
exports.findIndexValue = findIndexValue;
exports.someArray = someArray;
exports.log = log$2;
exports.speak = speak;
exports.someCat = someCat;
exports.someDog = someDog;
/*  Not a pure module */
