// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Function$Rationale = require("rationale/src/Function.js");

console.log("\n\n--------------------------------------------------------------------");

console.log("Hello, BuckleScript and Reason!");

var greeting = "foo";

console.log("Hello " + (String(greeting) + " from `console.log` using string templates"));

function log(prim) {
  console.log(prim);
  return /* () */0;
}

Pervasives.print_string("Hello, using OCaml `print_string`!\n");

function doubleInt(x) {
  return (x << 1);
}

function doubleFloat(x) {
  return x * 2;
}

function doubleString(param) {
  return Function$Rationale.$less$pipe$pipe((function (param) {
                return Function$Rationale.$less$pipe$pipe((function (prim) {
                              return String(prim);
                            }), doubleInt, param);
              }), Caml_format.caml_int_of_string, param);
}

function coinToString(x) {
  switch (x) {
    case 0 : 
        return "`x` was BTC";
    case 1 : 
        return "`x` was ETH";
    case 2 : 
        return "`x` was LTC";
    
  }
}

function eitherToString(data) {
  if (data.tag) {
    var x = data[0];
    if (x !== 0) {
      return "Right(" + (String(x) + (", " + (String(data[1]) + ")")));
    } else {
      return "Right where the first was 0";
    }
  } else {
    return "Left(" + (String(data[0]) + ")");
  }
}

function eitherToStringLog(param) {
  return Function$Rationale.$less$pipe$pipe((function (prim) {
                console.log(prim);
                return /* () */0;
              }), eitherToString, param);
}

function getPersonInfo(data) {
  var exit = 0;
  switch (data[/* name */0]) {
    case "Ally" : 
    case "Rob" : 
        exit = 1;
        break;
    default:
      return "Some other person with the name: \"" + (data[/* name */0] + ("\" is " + (String(data[/* age */1]) + " years old.")));
  }
  if (exit === 1) {
    return "\"" + (String(data[/* name */0]) + ("\" is " + (String(data[/* age */1]) + " years old")));
  }
  
}

function getNameVerbose(data) {
  if (data[/* name */0] === "Rob") {
    return "What's up Rob";
  } else {
    return "I don\'t know you " + (String(data) + ".name");
  }
}

function getNameShort(x) {
  if (x[/* name */0] === "Rob") {
    return "What's up Rob";
  } else {
    return "I don\'t know you " + (String(x) + ".name");
  }
}

function findIndexValue(needle, haystack) {
  if (haystack.length !== 0) {
    return haystack.findIndex((function (x) {
                  return Caml_obj.caml_equal(x, needle);
                }));
  }
  
}

var someArray = /* array */[
  "foo",
  "bar",
  "baz"
];

function speak(animal, extra) {
  var prim = animal[/* kind */0] ? "I\'m a smelly dog, I go by " + (String(animal) + (".name. Here\'s a thought about " + (String(extra) + "."))) : "Hi, I\'m a Cat by the name of " + (String(animal) + (".name and I want to tell you about " + (String(extra) + "!!")));
  console.log(prim);
  return animal;
}

var btc = /* BTC */0;

var eth = /* ETH */1;

var ltc = /* LTC */2;

var rob = /* record */[
  /* name */"Rob",
  /* age */31
];

var ally = /* record */[
  /* name */"Ally",
  /* age */30
];

var someCat = /* record */[
  /* kind : Cat */0,
  /* name */"pet1"
];

var someDog = /* record */[
  /* kind : Dog */1,
  /* name */"pet2"
];

exports.greeting = greeting;
exports.log = log;
exports.doubleInt = doubleInt;
exports.doubleFloat = doubleFloat;
exports.doubleString = doubleString;
exports.btc = btc;
exports.eth = eth;
exports.ltc = ltc;
exports.coinToString = coinToString;
exports.eitherToString = eitherToString;
exports.eitherToStringLog = eitherToStringLog;
exports.rob = rob;
exports.ally = ally;
exports.getPersonInfo = getPersonInfo;
exports.getNameVerbose = getNameVerbose;
exports.getNameShort = getNameShort;
exports.findIndexValue = findIndexValue;
exports.someArray = someArray;
exports.speak = speak;
exports.someCat = someCat;
exports.someDog = someDog;
/*  Not a pure module */
